### ISSUE TITLE
ProgrammingError at / (1146, u"Table 'blog.app_article' doesn't exist")

### ISSUE THREAD

**Issue by zhouyunfeng** [tomming233/blog#16]
ProgrammingError at /
(1146, u"Table 'blog.app_article' doesn't exist")

这个什么意思求助

**Comment by zhouyunfeng** [comment]
上述问题已经解决  运行之前同步一下数据库 python manage.py syncdb

新问题

41 | <a class="navbar-brand" href="       {% url 'app:index' %}       ">主页</a>


NoReverseMatch at /
u'app' is not a registered namespace

**Comment by zhouyunfeng** [comment]
1 a class="navbar-brand" href="       {% url 'app:index' %}

**Comment by zhouyunfeng** [comment]
ERROR 2018-03-20 15:35:31,282 base 14216 14856 Internal Server Error: /
Traceback (most recent call last):
  File "E:\Python27\lib\site-packages\django\core\handlers\base.py", line 164, in get_response
    response = response.render()
  File "E:\Python27\lib\site-packages\django\template\response.py", line 158, in render
    self.content = self.rendered_content
  File "E:\Python27\lib\site-packages\django\template\response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "E:\Python27\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "E:\Python27\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "E:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "E:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "E:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "E:\Python27\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "E:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "E:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "E:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "E:\Python27\lib\site-packages\django\template\defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "E:\Python27\lib\site-packages\django\template\defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "E:\Python27\lib\site-packages\django\core\urlresolvers.py", line 575, in reverse
    key)
NoReverseMatch: u'app' is not a registered namespace
